// This file was generated by the Makefile

#ifndef IMAGE_FILES_DEF
#define IMAGE_FILES_DEF

#define IMAGE_FONT "resources/font.img"
#define IMAGE_HEADLIGHT "resources/headlight.img"
#define IMAGE_TEST "resources/test.img"
#define IMAGE_SCRIBBLE "resources/scribble.img"
#define IMAGE_DANNY "resources/danny.img"
#define IMAGE_FLOOR "resources/floor.img"

#endif
